import {
    CheckCircleIcon,
    UserCircleIcon,
    PhoneIcon,
    DocumentTextIcon,
    CalendarIcon,
    CheckBadgeIcon,
    BriefcaseIcon,
    WrenchScrewdriverIcon,
    BuildingOfficeIcon,
    PaintBrushIcon,
    SparklesIcon,
    ArchiveBoxIcon,
    SunIcon,
    PlusCircleIcon,
    ChatBubbleBottomCenterTextIcon,
    TruckIcon,
    CreditCardIcon,
    ClipboardDocumentCheckIcon,
  } from "@heroicons/react/24/solid";
  
  export const iconMap: { [key: string]: React.ElementType } = {
    CheckCircleIcon,
    UserCircleIcon,
    PhoneIcon,
    DocumentTextIcon,
    CalendarIcon,
    CheckBadgeIcon,
    BriefcaseIcon,
    WrenchScrewdriverIcon,
    BuildingOfficeIcon,
    PaintBrushIcon,
    SparklesIcon,
    ArchiveBoxIcon,
    SunIcon,
    PlusCircleIcon,
    ChatBubbleBottomCenterTextIcon,
    TruckIcon,
    CreditCardIcon,
    ClipboardDocumentCheckIcon,
  };